# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-22 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Codigo del satelite, ejemplo FS2017', max_length=24, unique=True, verbose_name='Codigo del satelite')),
                ('description', models.CharField(blank=True, help_text='Descripcion', max_length=120, verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Orbit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eccentricity', models.FloatField()),
                ('semimajorAxis', models.FloatField()),
                ('inclination', models.FloatField()),
                ('longitudeAscendingNode', models.FloatField()),
                ('argumentPeriapsis', models.FloatField()),
                ('meanAnomaly', models.FloatField()),
                ('pyEpoch', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Satellite',
            fields=[
                ('node_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='DtnSatSimulator.Node')),
                ('noradId', models.IntegerField(null=True)),
                ('orbit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DtnSatSimulator.Orbit')),
            ],
            bases=('DtnSatSimulator.node',),
        ),
    ]
