# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-01 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constellation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la constelacion, ejemplo Iridium', max_length=100, unique=True, verbose_name='Nombre de la constelacion')),
            ],
        ),
        migrations.CreateModel(
            name='Hope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Codigo del satelite, ejemplo FS2017', max_length=24, unique=True, verbose_name='Codigo del satelite')),
                ('description', models.CharField(blank=True, help_text='Descripcion', max_length=120, verbose_name='Descripcion')),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Orbit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eccentricity', models.FloatField()),
                ('semimajorAxis', models.FloatField()),
                ('inclination', models.FloatField()),
                ('longitudeAscendingNode', models.FloatField()),
                ('argumentPeriapsis', models.FloatField()),
                ('meanAnomaly', models.FloatField()),
                ('pyEpoch', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(help_text='Modulo donde normalmente se usuario el parametro', max_length=64, verbose_name='Modulo')),
                ('key', models.CharField(help_text='Clave', max_length=24, verbose_name='Clave')),
                ('value', models.CharField(help_text='Valor del parametro', max_length=128, verbose_name='Valor')),
                ('description', models.TextField(default='Describir parametro aqui', help_text='Descripcion del parametro, donde se usa, para que?', verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Propagation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('final', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PropagationDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('dt', models.DateTimeField()),
                ('positionX', models.FloatField()),
                ('positionY', models.FloatField()),
                ('positionZ', models.FloatField()),
                ('velocityX', models.FloatField()),
                ('velocityY', models.FloatField()),
                ('velocityZ', models.FloatField()),
                ('earthDistance', models.FloatField(default=0.0)),
                ('propagation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propagationDetails', to='DtnSatSimulator.Propagation')),
            ],
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tleDateTime', models.DateTimeField(auto_now_add=True)),
                ('downloaded', models.DateTimeField(auto_now_add=True)),
                ('lines', models.TextField(max_length=124)),
            ],
            options={
                'get_latest_by': 'tleDateTime',
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='DtnSatSimulator.Message')),
            ],
        ),
        migrations.CreateModel(
            name='GroundStation',
            fields=[
                ('node_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='DtnSatSimulator.Node')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField()),
            ],
            bases=('DtnSatSimulator.node',),
        ),
        migrations.CreateModel(
            name='Satellite',
            fields=[
                ('node_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='DtnSatSimulator.Node')),
                ('noradId', models.IntegerField(help_text='Codigo norad del satelite', unique=True, verbose_name='Codigo norad del satelite')),
                ('active', models.BooleanField(default=True, verbose_name='Activacion/desactivacion del satelite')),
                ('notes', models.TextField(max_length=512, null=True, verbose_name='Observaciones sobre el satelite')),
            ],
            bases=('DtnSatSimulator.node',),
        ),
        migrations.AddField(
            model_name='propagation',
            name='tle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propagations', to='DtnSatSimulator.Tle'),
        ),
        migrations.AddField(
            model_name='node',
            name='constellations',
            field=models.ManyToManyField(blank=True, related_name='nodes', to='DtnSatSimulator.Constellation'),
        ),
        migrations.AddField(
            model_name='message',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinationMessages', to='DtnSatSimulator.Node'),
        ),
        migrations.AddField(
            model_name='message',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sourceMessages', to='DtnSatSimulator.Node'),
        ),
        migrations.AddField(
            model_name='hope',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DtnSatSimulator.Track'),
        ),
        migrations.AddField(
            model_name='tle',
            name='satellite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tles', to='DtnSatSimulator.Satellite'),
        ),
        migrations.AddField(
            model_name='propagation',
            name='satellite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propagations', to='DtnSatSimulator.Satellite'),
        ),
    ]
