# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-23 23:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DtnSatSimulator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='node',
            options={'ordering': ('code',)},
        ),
    ]
