# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-24 00:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DtnSatSimulator', '0002_auto_20160823_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='satellite',
            name='node_ptr',
        ),
        migrations.RemoveField(
            model_name='satellite',
            name='orbit',
        ),
        migrations.DeleteModel(
            name='Node',
        ),
        migrations.DeleteModel(
            name='Orbit',
        ),
        migrations.DeleteModel(
            name='Satellite',
        ),
    ]
