# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-01 19:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DtnSatSimulator', '0002_satellite_launchyear'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='satellite',
            name='launchYear',
        ),
        migrations.AddField(
            model_name='satellite',
            name='dtLaunch',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 1, 19, 6, 2, 255664)),
        ),
    ]
