# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-24 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DtnSatSimulator', '0003_auto_20160823_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constellation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la constelacion, ejemplo Iridium', max_length=100, unique=True, verbose_name='Nombre de la constelacion')),
            ],
        ),
    ]
