# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-01 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DtnSatSimulator', '0003_auto_20160901_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satellite',
            name='dtLaunch',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
