# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-24 00:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DtnSatSimulator', '0004_constellation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Codigo del satelite, ejemplo FS2017', max_length=24, unique=True, verbose_name='Codigo del satelite')),
                ('description', models.CharField(blank=True, help_text='Descripcion', max_length=120, verbose_name='Descripcion')),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Orbit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eccentricity', models.FloatField()),
                ('semimajorAxis', models.FloatField()),
                ('inclination', models.FloatField()),
                ('longitudeAscendingNode', models.FloatField()),
                ('argumentPeriapsis', models.FloatField()),
                ('meanAnomaly', models.FloatField()),
                ('pyEpoch', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='DtnSatSimulator.Message')),
            ],
        ),
        migrations.CreateModel(
            name='GroundStation',
            fields=[
                ('node_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='DtnSatSimulator.Node')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField()),
            ],
            bases=('DtnSatSimulator.node',),
        ),
        migrations.CreateModel(
            name='Satellite',
            fields=[
                ('node_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='DtnSatSimulator.Node')),
                ('noradId', models.IntegerField(null=True)),
                ('orbit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DtnSatSimulator.Orbit')),
            ],
            bases=('DtnSatSimulator.node',),
        ),
        migrations.AddField(
            model_name='node',
            name='constellations',
            field=models.ManyToManyField(blank=True, related_name='nodes', to='DtnSatSimulator.Constellation'),
        ),
        migrations.AddField(
            model_name='message',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinationMessages', to='DtnSatSimulator.Node'),
        ),
        migrations.AddField(
            model_name='message',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sourceMessages', to='DtnSatSimulator.Node'),
        ),
        migrations.AddField(
            model_name='hope',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DtnSatSimulator.Track'),
        ),
    ]
