# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-01 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DtnSatSimulator', '0005_auto_20160823_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(help_text='Modulo donde normalmente se usuario el parametro', max_length=64, verbose_name='Modulo')),
                ('key', models.CharField(help_text='Clave', max_length=24, verbose_name='Clave')),
                ('value', models.CharField(help_text='Valor del parametro', max_length=128, verbose_name='Valor')),
                ('description', models.TextField(default='Describir parametro aqui', help_text='Descripcion del parametro, donde se usa, para que?', verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Propagation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('final', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PropagationDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('dt', models.DateTimeField()),
                ('positionX', models.FloatField()),
                ('positionY', models.FloatField()),
                ('positionZ', models.FloatField()),
                ('velocityX', models.FloatField()),
                ('velocityY', models.FloatField()),
                ('velocityZ', models.FloatField()),
                ('earthDistance', models.FloatField(default=0.0)),
                ('propagation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propagationDetails', to='DtnSatSimulator.Propagation')),
            ],
        ),
        migrations.CreateModel(
            name='Tle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tleDateTime', models.DateTimeField(auto_now_add=True)),
                ('downloaded', models.DateTimeField(auto_now_add=True)),
                ('lines', models.TextField(max_length=124)),
            ],
            options={
                'get_latest_by': 'tleDateTime',
            },
        ),
        migrations.RemoveField(
            model_name='satellite',
            name='node_ptr',
        ),
        migrations.RemoveField(
            model_name='satellite',
            name='orbit',
        ),
        migrations.AddField(
            model_name='satellite',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activacion/desactivacion del satelite'),
        ),
        migrations.AddField(
            model_name='satellite',
            name='code',
            field=models.CharField(default='cd', help_text='Codigo del satelite, ejemplo FS2017', max_length=24, unique=True, verbose_name='Codigo del satelite'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='satellite',
            name='description',
            field=models.CharField(default='desc', help_text='Decripcion del satelite', max_length=100, unique=True, verbose_name='Decripcion del satelite'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='satellite',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='satellite',
            name='notes',
            field=models.TextField(max_length=512, null=True, verbose_name='Observaciones sobre el satelite'),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='noradId',
            field=models.IntegerField(default=1555, help_text='Codigo norad del satelite', unique=True, verbose_name='Codigo norad del satelite'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tle',
            name='satellite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tles', to='DtnSatSimulator.Satellite'),
        ),
        migrations.AddField(
            model_name='propagation',
            name='satellite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propagations', to='DtnSatSimulator.Satellite'),
        ),
        migrations.AddField(
            model_name='propagation',
            name='tle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propagations', to='DtnSatSimulator.Tle'),
        ),
    ]
